"use client";
import type { Metadata } from "next";
import { ToastContainer } from 'react-toastify';
import "./globals.css";
import { Suspense, useEffect } from "react";
import { BaseLoader } from "./components/baseLoader";
import { CONSTANT, ROUTES } from "./includes/constants";
import { useRouter } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
const navigate = useRouter();
useEffect(() => {
  const token = localStorage.getItem(CONSTANT.LocalStore.token);
  if(!token) {
    // navigate.replace(ROUTES.login);
  }
}, []);

  return (
    <html lang="en">
      <body
        className={`h-screen bg-white overflow-hidden`}
      >
        <Suspense
        fallback={<div className="flex items-center justify-center h-screen w-screen bg-white">
          <BaseLoader color="green" size="lg" />
          <div className="mt-4 text-[16px] font-medium text-black">Loading...</div>
          </div>}
        >
      {children}
      </Suspense>
      <ToastContainer />
      </body>
    </html>
  );
}
